version: "3.7"
services:
  app:
    build:
      args:
        user: timtinan37
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: icng
    container_name: icng-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - icng
  db:
    image: mysql:5.7
    container_name: icng-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - icng
  nginx:
    image: nginx:1.17-alpine
    container_name: icng-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - icng
networks:
  icng:
    driver: bridge